### ISSUE TITLE
Changing the MDP

### ISSUE THREAD

**Issue by rohithmacherla** [juanjose49/omscs-cs7641-machine-learning-assignment-4#15]
How can I change the MDP (graph and probabilities associated with each action)?

**Comment by juanjose49** [comment]
The probabilities associated with each action are dictated by what's written in [Movement.java](https://github.com/juanjose49/omscs-cs7641-machine-learning-assignment-4/blob/master/src/main/java/assignment4/util/Movement.java). I'm not sure what you mean by changing the graph.

**Comment by rohithmacherla** [comment]
I meant changing where the walls were in the plot, but I figured that out. How can I change the discount factor? Is there a way to create a 'bad' terminal state? Thanks!
