### ISSUE TITLE
Plot 

### ISSUE THREAD

**Issue by alinakhay** [juanjose49/omscs-cs7641-machine-learning-assignment-4#9]
Hi! Arrows are not displayed in red and blue plot (only values). Can you please suggest how to fix this? Thanks!

**Comment by juanjose49** [comment]
Hi Alina,

There should be a small check box on the bottom left of that view. It's
pretty small so you may have missed it.

Regards,
Juan

**Comment by alinakhay** [comment]
Thank you, very kind of you:) Found it!
